### ISSUE TITLE
在 uxcore-validator 新增验证规则

### ISSUE THREAD

**Issue by kangning1206** [uxcore/uxcore-validator#5]
# Decimal验证

现在的问题，验证是onChange时触发，因此在用户输入过程中会出现验证失败，过程中提示失败总别人提bug，传统的验证规则是结束后验证，已经不符合现在的操作了；
- 输入任意一个数字合法，比如1和0都合法，但输入“-”号也合法;
- 输入 0. 合法；
- 输入 0.2 合法；
- 输入01 非法，也就是说0后边只能是小数点
# 正Decimal 规则
# 负Decimal规则
# 最大Decimal
# isNotEmpty 文本框空判断，过滤空格，如果填写的是空格，则不通过，这个需要trim掉空格，再判断长度是否大于0，可以给验证器新增一个参数，是否过滤空格

**Comment by eternalsky** [comment]
## form 现在已支持 blur 时触发验证。

edit:
- isNum 增加限制规则 0002.12，被认定为非法数字
- 增加 isPositiveNum 和 isNegativeNum
- 关于 trim 空格这个，如果加参数的话，会破坏现有 validator 的使用方法，还是建议业务中有这个需求的情况下，加入一个过滤空格的判断。
