### ISSUE TITLE
URL校验正则表达式写法导致在校验带hash的URL时使浏览器假死

### ISSUE THREAD

**Issue by ex90rts** [uxcore/uxcore-validator#7]
目前的pattern：`/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/`

可使用以下字符串检测（请新开窗口测试）：`https://ehr.alibaba-inc.com/cominsu/mobile/index.htm?spm=0.0.0.0.FDs9NW#/`

这个URL校验比较基础，很多URL被判断为不合法，其实是没问题的，我建议只校验到域名部分，后面的Path不做校验，否则很难找到一个通用的正则来做这个事情

**Comment by eternalsky** [comment]
假死的原因查了下，应该是正则中的无限回溯造成的，即使不带#，query 的?也会造成这个问题，原因是 ([\/\w .-]_)_ 这一段并没有加入对 \? # 的认可，而且又要求到结尾，带?使得 url 校验不通过，导致正则需要不断回溯各种可能性来 check，需要大量的循环。我们加入 ?/# 之后的判断是否可行？
`/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\?\#\/\w\.-]*)\/?$/`
